name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: invoicer-chapter2
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_REPO }}/invoicer-chapter2

    steps:
      # 1. Скачать код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установить Go 1.10 (как в оригинале)
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.10'
        id: go

      # 3. Проверить версию Go
      - name: Print Go version
        run: echo "Go version: ${{ steps.go.outputs.go-version }}"

      # 4. Запустить тесты
      - name: Run tests
        run: |
          go test ./...

      # 5. Собрать бинарник
      - name: Build binary
        run: |
          mkdir -p bin
          go build -o bin/invoicer --ldflags '-extldflags "-static"' .

      # 6. Установить Docker и собрать образ
      - name: Set up Docker
        uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      # 7. Залогиниться в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Собрать Docker-образ
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest

      # 9. Сохранить хэш образа (как в CircleCI)
      - name: Save Docker image SHA
        run: |
          docker inspect ${{ env.DOCKER_IMAGE_NAME }}:latest --format='{{.Id}}' > docker-image-shasum256.txt
          cat docker-image-shasum256.txt

      # 10. Загрузить артефакт (SHA образа)
      - name: Upload SHA as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-sha
          path: docker-image-shasum256.txt